foreach(required BOOTLOADER_HEX APPLICATION_HEX OUTPUT_HEX)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()

file(READ "${BOOTLOADER_HEX}" bootloader_hex)
file(READ "${APPLICATION_HEX}" application_hex)
string(REGEX REPLACE ":00000001FF[\r\n]*$" "" bootloader_hex "${bootloader_hex}")
if(bootloader_hex MATCHES ":00000001FF")
  message(FATAL_ERROR "Bootloader HEX contains an unexpected embedded EOF record")
endif()
if(NOT application_hex MATCHES ":00000001FF[\r\n]*$")
  message(FATAL_ERROR "Application HEX does not end with an EOF record")
endif()
file(WRITE "${OUTPUT_HEX}" "${bootloader_hex}\n${application_hex}")
